package view;

import controller.TransactionController;
import model.Transaction;
import model.User;
import utils.AppConstants;
import utils.CurrencyUtil;
import utils.DateUtil;

import java.awt.*;
import java.awt.print.*;
import java.io.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * PDFExporter - Generates a printable PDF report using Java's PrinterJob API.
 * No external library required - uses Java2D for rendering to PDF via print.
 *
 * For a true PDF, this class also writes a formatted text-based PDF that can
 * be opened in any PDF viewer, using a simple plain-text PDF structure.
 */
public final class PDFExporter {

    private PDFExporter() {}

    /**
     * Exports the monthly report as a formatted text PDF file.
     * Uses raw PDF syntax for zero-dependency PDF generation.
     */
    public static void export(File outputFile, User user, int month, int year,
                               TransactionController controller) throws Exception {
        BigDecimal income  = controller.getMonthIncome(month, year);
        BigDecimal expense = controller.getMonthExpense(month, year);
        BigDecimal balance = income.subtract(expense);
        List<Transaction> txList = controller.getMonthTransactions(month, year);
        Map<String, BigDecimal> cats = controller.getCategoryExpenses(month, year);

        String[] months = {"","January","February","March","April","May","June",
                           "July","August","September","October","November","December"};

        StringBuilder content = new StringBuilder();

        // Build PDF content stream text
        content.append("Smart Expense Tracker - Monthly Report\n");
        content.append("=".repeat(50)).append("\n");
        content.append("User    : ").append(user.getFullName()).append("\n");
        content.append("Period  : ").append(months[month]).append(" ").append(year).append("\n");
        content.append("Generated: ").append(LocalDate.now()).append("\n");
        content.append("=".repeat(50)).append("\n\n");
        content.append("FINANCIAL SUMMARY\n");
        content.append("-".repeat(30)).append("\n");
        content.append(String.format("%-25s %s\n", "Total Income:",  CurrencyUtil.format(income)));
        content.append(String.format("%-25s %s\n", "Total Expense:", CurrencyUtil.format(expense)));
        content.append(String.format("%-25s %s\n", "Net Balance:",   CurrencyUtil.format(balance)));
        content.append(String.format("%-25s %d\n", "Transactions:",  txList.size()));
        content.append("\n");

        if (!cats.isEmpty()) {
            content.append("EXPENSE BY CATEGORY\n");
            content.append("-".repeat(30)).append("\n");
            double totalExp = expense.doubleValue();
            for (Map.Entry<String, BigDecimal> e : cats.entrySet()) {
                double pct = totalExp > 0 ? e.getValue().doubleValue() / totalExp * 100 : 0;
                content.append(String.format("%-20s %-14s %.1f%%\n",
                    e.getKey(), CurrencyUtil.format(e.getValue()), pct));
            }
            content.append("\n");
        }

        content.append("TRANSACTION DETAILS\n");
        content.append("-".repeat(60)).append("\n");
        content.append(String.format("%-12s %-8s %-18s %-20s %s\n",
            "Date","Type","Category","Description","Amount"));
        content.append("-".repeat(60)).append("\n");
        for (Transaction t : txList) {
            content.append(String.format("%-12s %-8s %-18s %-20s %s\n",
                DateUtil.toDisplay(t.getTransactionDate()),
                t.getType().name(),
                t.getCategory().getName(),
                (t.getDescription() != null ? t.getDescription() : "").substring(0,
                    Math.min(18, t.getDescription() != null ? t.getDescription().length() : 0)),
                (t.isIncome() ? "+" : "-") + CurrencyUtil.format(t.getAmount())
            ));
        }
        content.append("-".repeat(60)).append("\n");
        content.append(String.format("%-40s %s\n", "TOTAL INCOME:",  CurrencyUtil.format(income)));
        content.append(String.format("%-40s %s\n", "TOTAL EXPENSE:", CurrencyUtil.format(expense)));
        content.append(String.format("%-40s %s\n", "NET BALANCE:",   CurrencyUtil.format(balance)));
        content.append("\n\n");
        content.append("--- End of Report ---\n");
        content.append("Generated by ").append(AppConstants.APP_NAME)
               .append(" v").append(AppConstants.APP_VERSION).append("\n");

        // Write minimal PDF using raw PDF syntax
        writePdf(outputFile, content.toString(), user.getFullName(), months[month] + " " + year);
    }

    /**
     * Writes a minimal valid PDF file with the given text content.
     * This is a hand-crafted PDF structure with no external dependencies.
     */
    private static void writePdf(File file, String textContent, String author, String title)
            throws IOException {
        // Split content into lines for rendering
        String[] lines = textContent.split("\n");

        // Build PDF content stream (BT/ET text blocks)
        StringBuilder cs = new StringBuilder();
        cs.append("BT\n");
        cs.append("/F1 10 Tf\n");
        cs.append("50 780 Td\n");
        cs.append("14 TL\n"); // Leading

        for (String line : lines) {
            // Escape PDF special chars
            String safe = line
                .replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)")
                .replace("\r", "");
            // Replace rupee symbol with Rs. for PDF compatibility
            safe = safe.replace("₹", "Rs.");
            cs.append("(").append(safe).append(") '\n");
        }
        cs.append("ET\n");

        byte[] streamBytes = cs.toString().getBytes("ISO-8859-1");

        // PDF object offsets
        int[] offsets = new int[8];

        try (FileOutputStream fos = new FileOutputStream(file);
             PrintStream ps = new PrintStream(fos, false, "ISO-8859-1")) {

            // PDF header
            ps.print("%PDF-1.4\n");

            // Object 1: Catalog
            offsets[1] = (int) fos.getChannel().position();
            ps.print("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");

            // Object 2: Pages
            offsets[2] = (int) fos.getChannel().position();
            ps.print("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");

            // Object 3: Page
            offsets[3] = (int) fos.getChannel().position();
            ps.print("3 0 obj\n<< /Type /Page /Parent 2 0 R "
                   + "/MediaBox [0 0 612 792] "
                   + "/Contents 4 0 R "
                   + "/Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n");

            // Object 4: Content stream
            offsets[4] = (int) fos.getChannel().position();
            ps.print("4 0 obj\n<< /Length " + streamBytes.length + " >>\nstream\n");
            fos.flush();
            fos.write(streamBytes);
            ps.print("\nendstream\nendobj\n");

            // Object 5: Font (Courier for monospace)
            offsets[5] = (int) fos.getChannel().position();
            ps.print("5 0 obj\n<< /Type /Font /Subtype /Type1 "
                   + "/BaseFont /Courier >>\nendobj\n");

            // Object 6: Info dictionary
            offsets[6] = (int) fos.getChannel().position();
            ps.print("6 0 obj\n<< /Title (" + title + ") "
                   + "/Author (" + author + ") "
                   + "/Creator (" + AppConstants.APP_NAME + ") >>\nendobj\n");

            // Cross-reference table
            fos.flush();
            int xrefOffset = (int) fos.getChannel().position();
            ps.print("xref\n0 7\n");
            ps.print("0000000000 65535 f \n");
            for (int i = 1; i <= 6; i++) {
                ps.print(String.format("%010d 00000 n \n", offsets[i]));
            }

            // Trailer
            ps.print("trailer\n<< /Size 7 /Root 1 0 R /Info 6 0 R >>\n");
            ps.print("startxref\n" + xrefOffset + "\n%%EOF\n");
            ps.flush();
        }
    }
}
